/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyecto;

/**
 *
 * @author USUARIO
 */
public class JCarga extends javax.swing.JPanel {

    /**
     * Creates new form JCarga
     */
    public JCarga() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        Toneladas = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        CapacidadDeCarga1 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        Dimensiones = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setRequestFocusEnabled(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel10.setText("Toneladas");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        Toneladas.setForeground(new java.awt.Color(204, 204, 204));
        Toneladas.setText("Ingrese las toneladas");
        Toneladas.setBorder(null);
        add(Toneladas, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 260, 30));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 260, 10));

        jLabel11.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel11.setText("Capacidad de Carga");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        CapacidadDeCarga1.setForeground(new java.awt.Color(204, 204, 204));
        CapacidadDeCarga1.setText("Ingrese la capacidad de carga");
        CapacidadDeCarga1.setBorder(null);
        add(CapacidadDeCarga1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 260, 30));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 260, 10));

        jLabel12.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel12.setText("Dimensiones");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        Dimensiones.setForeground(new java.awt.Color(204, 204, 204));
        Dimensiones.setText("Ingrese las dimensiones");
        Dimensiones.setBorder(null);
        add(Dimensiones, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 260, 30));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 260, 10));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CapacidadDeCarga1;
    private javax.swing.JTextField Dimensiones;
    private javax.swing.JTextField Toneladas;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
