/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyecto;

/**
 *
 * @author USUARIO
 */
public class JTBus extends javax.swing.JPanel {

    /**
     * Creates new form JTBus
     */
    public JTBus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnAire = new javax.swing.ButtonGroup();
        BtnBanio = new javax.swing.ButtonGroup();
        jLabel12 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        NAsientos = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        NoAire = new javax.swing.JRadioButton();
        SiAire = new javax.swing.JRadioButton();
        SiBanio1 = new javax.swing.JRadioButton();
        NoBanio1 = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel12.setText("Baño");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, -1));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 260, 10));

        jLabel13.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel13.setText("N Asientos");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        NAsientos.setForeground(new java.awt.Color(204, 204, 204));
        NAsientos.setText("Ingrese los numeros de asientos");
        NAsientos.setBorder(null);
        add(NAsientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 260, 30));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 260, 10));

        jLabel14.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel14.setText("Aire acondicionado");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 260, 10));

        BtnAire.add(NoAire);
        NoAire.setText("No");
        add(NoAire, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, -1, -1));

        BtnAire.add(SiAire);
        SiAire.setText("Si");
        add(SiAire, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, -1));

        BtnBanio.add(SiBanio1);
        SiBanio1.setText("Si");
        add(SiBanio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, -1, -1));

        BtnBanio.add(NoBanio1);
        NoBanio1.setText("No");
        add(NoBanio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BtnAire;
    private javax.swing.ButtonGroup BtnBanio;
    private javax.swing.JTextField NAsientos;
    private javax.swing.JRadioButton NoAire;
    private javax.swing.JRadioButton NoBanio1;
    private javax.swing.JRadioButton SiAire;
    private javax.swing.JRadioButton SiBanio1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    // End of variables declaration//GEN-END:variables
}
