/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyecto;

/**
 *
 * @author USUARIO
 */
public class JTMoto extends javax.swing.JPanel {

    /**
     * Creates new form JTMoto
     */
    public JTMoto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnNCascos = new javax.swing.ButtonGroup();
        jLabel13 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        NCasco1 = new javax.swing.JRadioButton();
        NCasco2 = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel13.setText("N Cascos");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 260, 10));

        BtnNCascos.add(NCasco1);
        NCasco1.setText("1");
        add(NCasco1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        BtnNCascos.add(NCasco2);
        NCasco2.setText("2");
        add(NCasco2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BtnNCascos;
    private javax.swing.JRadioButton NCasco1;
    private javax.swing.JRadioButton NCasco2;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
