/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyecto;

import java.awt.Color;

/**
 *
 * @author USUARIO
 */
public class JTransporte extends javax.swing.JPanel {

    /**
     * Creates new form JTransporte
     */
    public JTransporte() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        nColor = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(580, 170));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel10.setText("Color");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        nColor.setForeground(new java.awt.Color(204, 204, 204));
        nColor.setText("Ingrese el color");
        nColor.setBorder(null);
        nColor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nColorMouseClicked(evt);
            }
        });
        nColor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nColorKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nColorKeyTyped(evt);
            }
        });
        add(nColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 260, 30));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 260, 10));
    }// </editor-fold>//GEN-END:initComponents

    private void nColorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nColorMouseClicked
        nColor();
    }//GEN-LAST:event_nColorMouseClicked

    private void nColorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nColorKeyPressed
        nColor();
    }//GEN-LAST:event_nColorKeyPressed

    private void nColorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nColorKeyTyped
        nColor();
    }//GEN-LAST:event_nColorKeyTyped

    private void nColor(){
        if (String.valueOf(nColor.getText()).equals("Ingrese el color")) {
            nColor.setText("");
            nColor.setForeground(Color.black);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField nColor;
    // End of variables declaration//GEN-END:variables
}
