/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto;


import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author USUARIO
 */
public class Registrar_clientes extends javax.swing.JFrame {
    private final String nArchivo="PersonaNatural.dat";
    private int xMouse;
    private int yMouse;
    private String codigo;
    private String Correo;

    /**
     * Creates new form Registrar_clientes
     */
    public Registrar_clientes() {
        initComponents();
        this.codigo=null;
        this.Correo=null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        hideBtn = new javax.swing.JPanel();
        hideTxt = new javax.swing.JLabel();
        exitBtn = new javax.swing.JPanel();
        exitTxt = new javax.swing.JLabel();
        backBtn = new javax.swing.JPanel();
        backTxt = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        Nombre = new javax.swing.JLabel();
        Apellidos = new javax.swing.JLabel();
        Dni = new javax.swing.JLabel();
        DVeri = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        Enviarcodigo = new javax.swing.JPanel();
        nEnviarcodigo = new javax.swing.JLabel();
        Codigo = new javax.swing.JLabel();
        nNombre = new javax.swing.JTextField();
        nDni = new javax.swing.JTextField();
        nEmail = new javax.swing.JTextField();
        nApellidos = new javax.swing.JTextField();
        nDigito = new javax.swing.JTextField();
        nCodigo = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        header1 = new javax.swing.JPanel();
        Guardar = new javax.swing.JPanel();
        Guardartxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(980, 570));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(980, 570));
        jPanel1.setPreferredSize(new java.awt.Dimension(980, 570));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setVerifyInputWhenFocusTarget(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hideBtn.setBackground(new java.awt.Color(255, 255, 255));

        hideTxt.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        hideTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hideTxt.setText("—");
        hideTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        hideTxt.setPreferredSize(new java.awt.Dimension(40, 40));
        hideTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hideTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hideTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hideTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout hideBtnLayout = new javax.swing.GroupLayout(hideBtn);
        hideBtn.setLayout(hideBtnLayout);
        hideBtnLayout.setHorizontalGroup(
            hideBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hideBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(hideTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        hideBtnLayout.setVerticalGroup(
            hideBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hideBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(hideTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(hideBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 0, -1, -1));

        exitBtn.setBackground(new java.awt.Color(255, 255, 255));

        exitTxt.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        exitTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitTxt.setText("X");
        exitTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        exitTxt.setPreferredSize(new java.awt.Dimension(40, 40));
        exitTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitBtnLayout = new javax.swing.GroupLayout(exitBtn);
        exitBtn.setLayout(exitBtnLayout);
        exitBtnLayout.setHorizontalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        exitBtnLayout.setVerticalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 0, -1, -1));

        backBtn.setBackground(new java.awt.Color(255, 255, 255));

        backTxt.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        backTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backTxt.setText("\t←");
        backTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        backTxt.setPreferredSize(new java.awt.Dimension(40, 40));
        backTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout backBtnLayout = new javax.swing.GroupLayout(backBtn);
        backBtn.setLayout(backBtnLayout);
        backBtnLayout.setHorizontalGroup(
            backBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(backTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        backBtnLayout.setVerticalGroup(
            backBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(backTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, -1));

        Nombre.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        Nombre.setText("Nombre");
        jPanel1.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 113, 124, -1));

        Apellidos.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        Apellidos.setText("Apellidos");
        jPanel1.add(Apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 169, -1, 38));

        Dni.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        Dni.setText("Dni");
        jPanel1.add(Dni, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 56, 38, 38));

        DVeri.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        DVeri.setText("Digito Verificador");
        jPanel1.add(DVeri, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 225, -1, 38));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(625, 81, -1, -1));

        Email.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        Email.setText("E-mail");
        jPanel1.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 287, 68, 39));

        Enviarcodigo.setBackground(new java.awt.Color(51, 153, 0));
        Enviarcodigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EnviarcodigoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EnviarcodigoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EnviarcodigoMouseExited(evt);
            }
        });
        Enviarcodigo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nEnviarcodigo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nEnviarcodigo.setForeground(new java.awt.Color(255, 255, 255));
        nEnviarcodigo.setText("Enviar codigo");
        Enviarcodigo.add(nEnviarcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 6, -1, 24));

        jPanel1.add(Enviarcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 290, 130, 40));

        Codigo.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        Codigo.setText("Codigo");
        jPanel1.add(Codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 350, 68, 38));

        nNombre.setForeground(new java.awt.Color(204, 204, 204));
        nNombre.setText("Ingrese su nombre");
        nNombre.setBorder(null);
        nNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nNombreMouseClicked(evt);
            }
        });
        nNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nNombreKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nNombreKeyTyped(evt);
            }
        });
        jPanel1.add(nNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 356, 38));

        nDni.setForeground(new java.awt.Color(204, 204, 204));
        nDni.setText("Ingrese su dni");
        nDni.setBorder(null);
        nDni.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nDniMouseClicked(evt);
            }
        });
        nDni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nDniKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nDniKeyTyped(evt);
            }
        });
        jPanel1.add(nDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 356, 38));

        nEmail.setForeground(new java.awt.Color(204, 204, 204));
        nEmail.setText("Ingrese su e-mail");
        nEmail.setBorder(null);
        nEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nEmailMouseClicked(evt);
            }
        });
        nEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nEmailKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nEmailKeyTyped(evt);
            }
        });
        jPanel1.add(nEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 356, 38));

        nApellidos.setForeground(new java.awt.Color(204, 204, 204));
        nApellidos.setText("Ingrese sus apellidos");
        nApellidos.setBorder(null);
        nApellidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nApellidosMouseClicked(evt);
            }
        });
        nApellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nApellidosKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nApellidosKeyTyped(evt);
            }
        });
        jPanel1.add(nApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 356, 38));

        nDigito.setForeground(new java.awt.Color(204, 204, 204));
        nDigito.setText("Ingrese el digito verificador del dni");
        nDigito.setBorder(null);
        nDigito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nDigitoMouseClicked(evt);
            }
        });
        nDigito.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nDigitoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nDigitoKeyTyped(evt);
            }
        });
        jPanel1.add(nDigito, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 356, 38));

        nCodigo.setForeground(new java.awt.Color(204, 204, 204));
        nCodigo.setText("Ingrese su codigo enviado a su e-mail");
        nCodigo.setBorder(null);
        nCodigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nCodigoMouseClicked(evt);
            }
        });
        nCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nCodigoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nCodigoKeyTyped(evt);
            }
        });
        jPanel1.add(nCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 356, 38));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 360, 10));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, 360, 10));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 360, 10));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 360, 10));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 360, 10));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 360, 10));

        header1.setBackground(new java.awt.Color(255, 255, 255));
        header1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                header1MouseDragged(evt);
            }
        });
        header1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                header1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout header1Layout = new javax.swing.GroupLayout(header1);
        header1.setLayout(header1Layout);
        header1Layout.setHorizontalGroup(
            header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );
        header1Layout.setVerticalGroup(
            header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(header1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 810, 40));

        Guardar.setBackground(new java.awt.Color(51, 153, 0));
        Guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GuardarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                GuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                GuardarMouseExited(evt);
            }
        });
        Guardar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Guardartxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Guardartxt.setForeground(new java.awt.Color(255, 255, 255));
        Guardartxt.setText("Guardar");
        Guardar.add(Guardartxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 6, -1, 24));

        jPanel1.add(Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 480, 130, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen()-60;
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void backTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backTxtMouseExited
        backBtn.setBackground(Color.white);
        backTxt.setForeground(Color.black);
    }//GEN-LAST:event_backTxtMouseExited

    private void backTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backTxtMouseEntered
        backBtn.setBackground(new Color(51,153,0));
        backTxt.setForeground(Color.white);
    }//GEN-LAST:event_backTxtMouseEntered

    private void backTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backTxtMouseClicked
        dispose();
        new MenuAdministrador().setVisible(true);
    }//GEN-LAST:event_backTxtMouseClicked

    private void exitTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseExited
        exitBtn.setBackground(Color.white);
        exitTxt.setForeground(Color.black);
    }//GEN-LAST:event_exitTxtMouseExited

    private void exitTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseEntered
        exitBtn.setBackground(Color.red);
        exitTxt.setForeground(Color.white);
    }//GEN-LAST:event_exitTxtMouseEntered

    private void exitTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitTxtMouseClicked

    private void hideTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hideTxtMouseExited
        hideBtn.setBackground(Color.white);
        hideTxt.setForeground(Color.black);
    }//GEN-LAST:event_hideTxtMouseExited

    private void hideTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hideTxtMouseEntered
        hideBtn.setBackground(Color.blue);
        hideTxt.setForeground(Color.white);
    }//GEN-LAST:event_hideTxtMouseEntered

    private void hideTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hideTxtMouseClicked
        setExtendedState(ICONIFIED);
    }//GEN-LAST:event_hideTxtMouseClicked

    private void EnviarcodigoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EnviarcodigoMouseClicked
        String mcodigo="";

            //Thread.sleep(1000);
            
        
            int aleatorio;
            for(int i=0;i<4;i++){
                aleatorio=(int) (Math.random()*10);
                mcodigo+=Integer.toString(aleatorio);
            }
            Sendmail m= new Sendmail(nEmail.getText(),"Código de verificación ",mcodigo);
            m.mail();
        this.Correo=nEmail.getText();
        this.codigo=mcodigo;
        JOptionPane.showMessageDialog(null,"Codigo enviado, revise su correo",
                    "Enviar Codigo",JOptionPane.INFORMATION_MESSAGE);
       
    }//GEN-LAST:event_EnviarcodigoMouseClicked

    private void EnviarcodigoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EnviarcodigoMouseEntered
        Enviarcodigo.setBackground(new Color(67, 180, 10));
    }//GEN-LAST:event_EnviarcodigoMouseEntered

    private void EnviarcodigoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EnviarcodigoMouseExited
        Enviarcodigo.setBackground(new Color(51,153,0));
    }//GEN-LAST:event_EnviarcodigoMouseExited

    private void nDniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nDniMouseClicked
        nDni();
    }//GEN-LAST:event_nDniMouseClicked

    private void nDniKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nDniKeyPressed
        nDni();
    }//GEN-LAST:event_nDniKeyPressed

    private void nDniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nDniKeyTyped
        nDni();
    }//GEN-LAST:event_nDniKeyTyped

    private void nNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nNombreKeyPressed
        nNombre();
    }//GEN-LAST:event_nNombreKeyPressed

    private void nNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nNombreKeyTyped
        nNombre();
    }//GEN-LAST:event_nNombreKeyTyped

    private void nNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nNombreMouseClicked
        nNombre();
    }//GEN-LAST:event_nNombreMouseClicked

    private void header1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_header1MouseDragged
        int x = evt.getXOnScreen()-60;
        int y = evt.getYOnScreen();
        this.setLocation(x  - xMouse, y - yMouse);
    }//GEN-LAST:event_header1MouseDragged

    private void header1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_header1MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_header1MousePressed

    private void nApellidosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nApellidosKeyPressed
        nApellidos();
    }//GEN-LAST:event_nApellidosKeyPressed

    private void nApellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nApellidosKeyTyped
        nApellidos();
    }//GEN-LAST:event_nApellidosKeyTyped

    private void nApellidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nApellidosMouseClicked
        nApellidos();
    }//GEN-LAST:event_nApellidosMouseClicked

    private void nDigitoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nDigitoKeyPressed
        nDigito();
    }//GEN-LAST:event_nDigitoKeyPressed

    private void nDigitoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nDigitoKeyTyped
        nDigito();
    }//GEN-LAST:event_nDigitoKeyTyped

    private void nDigitoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nDigitoMouseClicked
        nDigito();
    }//GEN-LAST:event_nDigitoMouseClicked

    private void nEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nEmailKeyPressed
        nEmail();
    }//GEN-LAST:event_nEmailKeyPressed

    private void nEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nEmailKeyTyped
        nEmail();
    }//GEN-LAST:event_nEmailKeyTyped

    private void nEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nEmailMouseClicked
        nEmail();
    }//GEN-LAST:event_nEmailMouseClicked

    private void nCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nCodigoKeyPressed
        nCodigo();
    }//GEN-LAST:event_nCodigoKeyPressed

    private void nCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nCodigoKeyTyped
        nCodigo();
    }//GEN-LAST:event_nCodigoKeyTyped

    private void nCodigoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nCodigoMouseClicked
        nCodigo();
    }//GEN-LAST:event_nCodigoMouseClicked

    private void GuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuardarMouseClicked

        int dni=0,c_verificador=0,codigo=0;
        try{
            if(8==nDni.getText().length()){
                dni=Integer.parseInt(nDni.getText());
            }
            else throw new NumberFormatException();
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null,"Ingrese 8 numeros en el dni",
                    "ERROR",JOptionPane.ERROR_MESSAGE);
            nDni.setText("");
        }
        try{
            c_verificador=Integer.parseInt(nDigito.getText());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null,"Ingrese numeros el digito",
                    "ERROR",JOptionPane.ERROR_MESSAGE);
            nDigito.setText("");
        }
        try{
            codigo=Integer.parseInt(nCodigo.getText());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null,"Ingrese numeros en el codigo",
                    "ERROR",JOptionPane.ERROR_MESSAGE);
            nCodigo.setText("");
        }
        this.codigo="1";
        if(this.codigo!=null){
            PersonaNatural p=new PersonaNatural(dni);
            p.Hallarcodigoverificador();
            p.Hallar_datos();
       
            if((p.getC_verificador()!=null && p.getApellidos()!=null) && p.getNombre()!=null){
               if(p.getC_verificador().equals(nDigito.getText()) && p.getApellidos().equalsIgnoreCase(nApellidos.getText())
               &&p.getNombre().equalsIgnoreCase(nNombre.getText()) && this.codigo.equals(nCodigo.getText())
                       /*&& nEmail.getText().equals(this.Correo)*/){
                        p.setCorreo(this.Correo);
                        if(SerializarObjeto.serializarObjeto(nArchivo,p,PersonaNatural.class)){
                            JOptionPane.showMessageDialog(null,"Registro de cliente terminado con exito",
                        "Listo",JOptionPane.INFORMATION_MESSAGE);
                        }else {
                            JOptionPane.showMessageDialog(null,"Error en escritura",
                        "Listo",JOptionPane.INFORMATION_MESSAGE);
                        }
                    
                    this.codigo=null;
               }else{
                   JOptionPane.showMessageDialog(null,"Error datos no conciden, intente de nuevo",
                        "ERROR",JOptionPane.ERROR_MESSAGE);
               }
            }
            else{
                JOptionPane.showMessageDialog(null,"Error en obtener datos, Intente mas tarde",
                        "ERROR",JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null,"Haga click en enviar codigo, luego ingrese el codigo que se le envia "
                    + "a su correo","Verifcar codigo",JOptionPane.ERROR_MESSAGE);
        }
        
        
        
        
    }//GEN-LAST:event_GuardarMouseClicked

    private void GuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuardarMouseEntered
        Guardar.setBackground(new Color(67, 180, 10));
    }//GEN-LAST:event_GuardarMouseEntered

    private void GuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuardarMouseExited
        Guardar.setBackground(new Color(51,153,0));
    }//GEN-LAST:event_GuardarMouseExited
                                   

    private void nDni(){
        if (String.valueOf(nDni.getText()).equals("Ingrese su dni")) {
            nDni.setText("");
            nDni.setForeground(Color.black);
        }
        if (nNombre.getText().isEmpty()) {
            nNombre.setText("Ingrese su nombre");
            nNombre.setForeground(Color.gray);
        }
        if (nApellidos.getText().isEmpty()) {
            nApellidos.setText("Ingrese sus apellidos");
            nApellidos.setForeground(Color.gray);
        }
        if (nDigito.getText().isEmpty()) {
            nDigito.setText("Ingrese el digito verificador del dni");
            nDigito.setForeground(Color.gray);
        }
        if (nEmail.getText().isEmpty()) {
            nEmail.setText("Ingrese su e-mail");
            nEmail.setForeground(Color.gray);
        }
        if (nCodigo.getText().isEmpty()) {
            nCodigo.setText("Ingrese su codigo enviado a su e-mail");
            nCodigo.setForeground(Color.gray);
        }
        
    }
    
    private void nNombre(){
        if (String.valueOf(nNombre.getText()).equals("Ingrese su nombre")) {
            nNombre.setText("");
            nNombre.setForeground(Color.black);
        }
        if (nDni.getText().isEmpty()) {
            nDni.setText("Ingrese su dni");
            nDni.setForeground(Color.gray);
        }
        if (nApellidos.getText().isEmpty()) {
            nApellidos.setText("Ingrese sus apellidos");
            nApellidos.setForeground(Color.gray);
        }
        if (nDigito.getText().isEmpty()) {
            nDigito.setText("Ingrese el digito verificador del dni");
            nDigito.setForeground(Color.gray);
        }
        if (nEmail.getText().isEmpty()) {
            nEmail.setText("Ingrese su e-mail");
            nEmail.setForeground(Color.gray);
        }
        if (nCodigo.getText().isEmpty()) {
            nCodigo.setText("Ingrese su codigo enviado a su e-mail");
            nCodigo.setForeground(Color.gray);
        }
        
    }
    
    private void nApellidos(){
        if (String.valueOf(nApellidos.getText()).equals("Ingrese sus apellidos")) {
            nApellidos.setText("");
            nApellidos.setForeground(Color.black);
        }
        if (nDni.getText().isEmpty()) {
            nDni.setText("Ingrese su dni");
            nDni.setForeground(Color.gray);
        }
        if (nNombre.getText().isEmpty()) {
            nNombre.setText("Ingrese su nombre");
            nNombre.setForeground(Color.gray);
        }
        if (nDigito.getText().isEmpty()) {
            nDigito.setText("Ingrese el digito verificador del dni");
            nDigito.setForeground(Color.gray);
        }
        if (nEmail.getText().isEmpty()) {
            nEmail.setText("Ingrese su e-mail");
            nEmail.setForeground(Color.gray);
        }
        if (nCodigo.getText().isEmpty()) {
            nCodigo.setText("Ingrese su codigo enviado a su e-mail");
            nCodigo.setForeground(Color.gray);
        }
        
    }
    
    private void nDigito(){
        if (String.valueOf(nDigito.getText()).equals("Ingrese el digito verificador del dni")) {
            nDigito.setText("");
            nDigito.setForeground(Color.black);
        }
        if (nDni.getText().isEmpty()) {
            nDni.setText("Ingrese su dni");
            nDni.setForeground(Color.gray);
        }
        if (nNombre.getText().isEmpty()) {
            nNombre.setText("Ingrese su nombre");
            nNombre.setForeground(Color.gray);
        }
        if (nApellidos.getText().isEmpty()) {
            nApellidos.setText("Ingrese sus apellidos");
            nApellidos.setForeground(Color.gray);
        }
        if (nEmail.getText().isEmpty()) {
            nEmail.setText("Ingrese su e-mail");
            nEmail.setForeground(Color.gray);
        }
        if (nCodigo.getText().isEmpty()) {
            nCodigo.setText("Ingrese su codigo enviado a su e-mail");
            nCodigo.setForeground(Color.gray);
        }
        
    }
    
    private void nEmail(){
        if (String.valueOf(nEmail.getText()).equals("Ingrese su e-mail")) {
            nEmail.setText("");
            nEmail.setForeground(Color.black);
        }
        if (nDni.getText().isEmpty()) {
            nDni.setText("Ingrese su dni");
            nDni.setForeground(Color.gray);
        }
        if (nNombre.getText().isEmpty()) {
            nNombre.setText("Ingrese su nombre");
            nNombre.setForeground(Color.gray);
        }
        if (nApellidos.getText().isEmpty()) {
            nApellidos.setText("Ingrese sus apellidos");
            nApellidos.setForeground(Color.gray);
        }
        if (nDigito.getText().isEmpty()) {
            nDigito.setText("Ingrese el digito verificador del dni");
            nDigito.setForeground(Color.gray);
        }
        if (nCodigo.getText().isEmpty()) {
            nCodigo.setText("Ingrese su codigo enviado a su e-mail");
            nCodigo.setForeground(Color.gray);
        }
    }   
    
    private void nCodigo(){
        if (String.valueOf(nCodigo.getText()).equals("Ingrese su codigo enviado a su e-mail")) {
            nCodigo.setText("");
            nCodigo.setForeground(Color.black);
        }
        if (nDni.getText().isEmpty()) {
            nDni.setText("Ingrese su dni");
            nDni.setForeground(Color.gray);
        }
        if (nNombre.getText().isEmpty()) {
            nNombre.setText("Ingrese su nombre");
            nNombre.setForeground(Color.gray);
        }
        if (nApellidos.getText().isEmpty()) {
            nApellidos.setText("Ingrese sus apellidos");
            nApellidos.setForeground(Color.gray);
        }
        if (nDigito.getText().isEmpty()) {
            nDigito.setText("Ingrese el digito verificador del dni");
            nDigito.setForeground(Color.gray);
        }
        if (nEmail.getText().isEmpty()) {
            nEmail.setText("Ingrese su e-mail");
            nEmail.setForeground(Color.gray);
        }
    }  
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrar_clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrar_clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrar_clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrar_clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrar_clientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Apellidos;
    private javax.swing.JLabel Codigo;
    private javax.swing.JLabel DVeri;
    private javax.swing.JLabel Dni;
    private javax.swing.JLabel Email;
    private javax.swing.JPanel Enviarcodigo;
    private javax.swing.JPanel Guardar;
    private javax.swing.JLabel Guardartxt;
    private javax.swing.JLabel Nombre;
    private javax.swing.JPanel backBtn;
    private javax.swing.JLabel backTxt;
    private javax.swing.JPanel exitBtn;
    private javax.swing.JLabel exitTxt;
    private javax.swing.JPanel header;
    private javax.swing.JPanel header1;
    private javax.swing.JPanel hideBtn;
    private javax.swing.JLabel hideTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField nApellidos;
    private javax.swing.JTextField nCodigo;
    private javax.swing.JTextField nDigito;
    private javax.swing.JTextField nDni;
    private javax.swing.JTextField nEmail;
    private javax.swing.JLabel nEnviarcodigo;
    private javax.swing.JTextField nNombre;
    // End of variables declaration//GEN-END:variables
}
