/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto;

import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.netbeans.lib.awtextra.AbsoluteLayout;

/**
 *
 * @author USUARIO
 */
public class RegistrarVehiculo extends javax.swing.JFrame {
    
    JFileChooser seleccionar = new JFileChooser();
    File archivo;
    byte [] imagen;
    FileInputStream entrada;
    FileOutputStream salida;
    private int xMouse;
    private int yMouse;
    public RegistrarVehiculo() {
        initComponents();
        TipoDeVehiculo2.setText("");
        OpCarga.setVisible(false);
        OpTransporte.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Carropng = new javax.swing.JLabel();
        SubircarroBtn = new javax.swing.JPanel();
        SubirCarroTxt = new javax.swing.JLabel();
        GuardarBtn = new javax.swing.JPanel();
        GuardarTxt = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        exitBtn = new javax.swing.JPanel();
        exitTxt = new javax.swing.JLabel();
        hideBtn = new javax.swing.JPanel();
        hideTxt = new javax.swing.JLabel();
        backBtn = new javax.swing.JPanel();
        backTxt = new javax.swing.JLabel();
        TipoDeVehiculo2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Seguro = new javax.swing.JTextField();
        CodigoProducto = new javax.swing.JTextField();
        Marca = new javax.swing.JTextField();
        Modelo = new javax.swing.JTextField();
        AiodeFabricacion = new javax.swing.JTextField();
        Transmicion = new javax.swing.JTextField();
        Combustible = new javax.swing.JTextField();
        Precio = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        CodigoPlaca = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        OpVehiculo = new javax.swing.JComboBox<>();
        ContenidoToC = new javax.swing.JPanel();
        OpCarga = new javax.swing.JComboBox<>();
        ContenidoT = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        TipoDeVehiculo = new javax.swing.JLabel();
        OpTransporte = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(980, 570));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Carropng.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(Carropng, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 530, 280, 170));

        SubircarroBtn.setBackground(new java.awt.Color(51, 153, 0));

        SubirCarroTxt.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        SubirCarroTxt.setForeground(new java.awt.Color(255, 255, 255));
        SubirCarroTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SubirCarroTxt.setText("Cargar imagen");
        SubirCarroTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        SubirCarroTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubirCarroTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SubirCarroTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SubirCarroTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout SubircarroBtnLayout = new javax.swing.GroupLayout(SubircarroBtn);
        SubircarroBtn.setLayout(SubircarroBtnLayout);
        SubircarroBtnLayout.setHorizontalGroup(
            SubircarroBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SubircarroBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(SubirCarroTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        SubircarroBtnLayout.setVerticalGroup(
            SubircarroBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SubircarroBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(SubirCarroTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(SubircarroBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 460, 130, 40));

        GuardarBtn.setBackground(new java.awt.Color(51, 153, 0));

        GuardarTxt.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        GuardarTxt.setForeground(new java.awt.Color(255, 255, 255));
        GuardarTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GuardarTxt.setText("Guardar");
        GuardarTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        GuardarTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GuardarTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                GuardarTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                GuardarTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout GuardarBtnLayout = new javax.swing.GroupLayout(GuardarBtn);
        GuardarBtn.setLayout(GuardarBtnLayout);
        GuardarBtnLayout.setHorizontalGroup(
            GuardarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GuardarBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(GuardarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        GuardarBtnLayout.setVerticalGroup(
            GuardarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GuardarBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(GuardarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(GuardarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 670, 130, 40));

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1060, Short.MAX_VALUE)
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel2.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 1060, 40));

        exitBtn.setBackground(new java.awt.Color(255, 255, 255));

        exitTxt.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        exitTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitTxt.setText("X");
        exitTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        exitTxt.setPreferredSize(new java.awt.Dimension(40, 40));
        exitTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitBtnLayout = new javax.swing.GroupLayout(exitBtn);
        exitBtn.setLayout(exitBtnLayout);
        exitBtnLayout.setHorizontalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(exitBtnLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(exitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        exitBtnLayout.setVerticalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(exitBtnLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(exitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel2.add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 0, -1, 40));

        hideBtn.setBackground(new java.awt.Color(255, 255, 255));

        hideTxt.setFont(new java.awt.Font("Segoe UI Black", 2, 24)); // NOI18N
        hideTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hideTxt.setText("—");
        hideTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        hideTxt.setPreferredSize(new java.awt.Dimension(40, 40));
        hideTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hideTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hideTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hideTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout hideBtnLayout = new javax.swing.GroupLayout(hideBtn);
        hideBtn.setLayout(hideBtnLayout);
        hideBtnLayout.setHorizontalGroup(
            hideBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(hideBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(hideBtnLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(hideTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        hideBtnLayout.setVerticalGroup(
            hideBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(hideBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(hideBtnLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(hideTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel2.add(hideBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 0, 40, 40));

        backBtn.setBackground(new java.awt.Color(255, 255, 255));

        backTxt.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        backTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backTxt.setText("\t←");
        backTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        backTxt.setPreferredSize(new java.awt.Dimension(40, 40));
        backTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout backBtnLayout = new javax.swing.GroupLayout(backBtn);
        backBtn.setLayout(backBtnLayout);
        backBtnLayout.setHorizontalGroup(
            backBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(backTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        backBtnLayout.setVerticalGroup(
            backBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(backTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        TipoDeVehiculo2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        TipoDeVehiculo2.setText("Tipo de Vehiculo");
        jPanel2.add(TipoDeVehiculo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel3.setText("Marca");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel4.setText("Modelo ");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel5.setText("Año de Fabricacion");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel6.setText("Transmicion");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel1.setText("Combustible");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel7.setText("Precio De Alquiler x dia");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));

        Seguro.setForeground(new java.awt.Color(204, 204, 204));
        Seguro.setText("Ingrese el seguro");
        Seguro.setBorder(null);
        Seguro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SeguroMouseClicked(evt);
            }
        });
        Seguro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SeguroKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                SeguroKeyTyped(evt);
            }
        });
        jPanel2.add(Seguro, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 260, 30));

        CodigoProducto.setForeground(new java.awt.Color(153, 153, 153));
        CodigoProducto.setText("Ingrese el codigo de producto");
        CodigoProducto.setBorder(null);
        CodigoProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CodigoProductoMouseClicked(evt);
            }
        });
        CodigoProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CodigoProductoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CodigoProductoKeyTyped(evt);
            }
        });
        jPanel2.add(CodigoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 260, 30));

        Marca.setForeground(new java.awt.Color(204, 204, 204));
        Marca.setText("Ingrese la marca");
        Marca.setBorder(null);
        Marca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MarcaMouseClicked(evt);
            }
        });
        Marca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                MarcaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                MarcaKeyTyped(evt);
            }
        });
        jPanel2.add(Marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 260, 30));

        Modelo.setForeground(new java.awt.Color(204, 204, 204));
        Modelo.setText("Ingrese el modelo");
        Modelo.setBorder(null);
        Modelo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ModeloMouseClicked(evt);
            }
        });
        Modelo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ModeloKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ModeloKeyTyped(evt);
            }
        });
        jPanel2.add(Modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 260, 30));

        AiodeFabricacion.setForeground(new java.awt.Color(204, 204, 204));
        AiodeFabricacion.setText("Ingrese el año de fabricacion");
        AiodeFabricacion.setBorder(null);
        AiodeFabricacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AiodeFabricacionMouseClicked(evt);
            }
        });
        AiodeFabricacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AiodeFabricacionKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                AiodeFabricacionKeyTyped(evt);
            }
        });
        jPanel2.add(AiodeFabricacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 260, 30));

        Transmicion.setForeground(new java.awt.Color(204, 204, 204));
        Transmicion.setText("Ingrese la transmicion");
        Transmicion.setBorder(null);
        Transmicion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TransmicionMouseClicked(evt);
            }
        });
        Transmicion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TransmicionKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TransmicionKeyTyped(evt);
            }
        });
        jPanel2.add(Transmicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 260, 30));

        Combustible.setForeground(new java.awt.Color(204, 204, 204));
        Combustible.setText("Ingrese el combustible");
        Combustible.setBorder(null);
        Combustible.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CombustibleMouseClicked(evt);
            }
        });
        Combustible.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CombustibleKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CombustibleKeyTyped(evt);
            }
        });
        jPanel2.add(Combustible, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 260, 30));

        Precio.setForeground(new java.awt.Color(204, 204, 204));
        Precio.setText("Ingrese el precio de alquiler x dia");
        Precio.setBorder(null);
        Precio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PrecioMouseClicked(evt);
            }
        });
        Precio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PrecioKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PrecioKeyTyped(evt);
            }
        });
        jPanel2.add(Precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 260, 30));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, 260, 10));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 260, 10));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 260, 10));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 260, 10));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 260, 10));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 260, 10));

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 260, 10));

        jSeparator8.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 260, 10));

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel9.setText("Seguro");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel8.setText("Codigo Placa");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, -1, -1));

        CodigoPlaca.setForeground(new java.awt.Color(204, 204, 204));
        CodigoPlaca.setText("Ingrese el codigo de placa");
        CodigoPlaca.setBorder(null);
        CodigoPlaca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CodigoPlacaMouseClicked(evt);
            }
        });
        CodigoPlaca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CodigoPlacaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CodigoPlacaKeyTyped(evt);
            }
        });
        jPanel2.add(CodigoPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, 260, 30));

        jSeparator9.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 260, 10));

        OpVehiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "","Transporte", "Carga"}));
        OpVehiculo.setBorder(null);
        OpVehiculo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                OpVehiculoItemStateChanged(evt);
            }
        });
        jPanel2.add(OpVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, 140, -1));

        ContenidoToC.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout ContenidoToCLayout = new javax.swing.GroupLayout(ContenidoToC);
        ContenidoToC.setLayout(ContenidoToCLayout);
        ContenidoToCLayout.setHorizontalGroup(
            ContenidoToCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );
        ContenidoToCLayout.setVerticalGroup(
            ContenidoToCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );

        jPanel2.add(ContenidoToC, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 100, 580, 350));

        OpCarga.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "","Camion", "Trailer" }));
        OpCarga.setBorder(null);
        OpCarga.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                OpCargaItemStateChanged(evt);
            }
        });
        jPanel2.add(OpCarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 70, 140, -1));

        ContenidoT.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout ContenidoTLayout = new javax.swing.GroupLayout(ContenidoT);
        ContenidoT.setLayout(ContenidoTLayout);
        ContenidoTLayout.setHorizontalGroup(
            ContenidoTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );
        ContenidoTLayout.setVerticalGroup(
            ContenidoTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );

        jPanel2.add(ContenidoT, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 560, 170));

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel10.setText("Codigo Producto");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        TipoDeVehiculo.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        TipoDeVehiculo.setText("Tipo de Vehiculo : ");
        jPanel2.add(TipoDeVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, -1, -1));

        OpTransporte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "","Moto", "Bus", "Auto"}));
        OpTransporte.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                OpTransporteItemStateChanged(evt);
            }
        });
        jPanel2.add(OpTransporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 70, 140, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1225, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubirCarroTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubirCarroTxtMouseClicked

        if(this.seleccionar.showDialog(null,"Abrir")==JFileChooser.APPROVE_OPTION){
            this.archivo=this.seleccionar.getSelectedFile();
            if(this.archivo.canRead()){
                if(this.archivo.getName().endsWith("png")||this.archivo.getName().endsWith("PNG")){//subir imagen en png
                    this.imagen=AbrirArchivo(this.archivo);
                    ImageIcon ii=new ImageIcon(this.imagen);
                    Image conversion=ii.getImage();//cambiar de tamanio
                    Image tamanio=conversion.getScaledInstance(280, 170, Image.SCALE_SMOOTH);
                    Carropng.setIcon(new ImageIcon(tamanio));
                }
                else{
                    JOptionPane.showMessageDialog(null,"Archivo no cargado");
                }
            }
        }

    }//GEN-LAST:event_SubirCarroTxtMouseClicked

    private void SubirCarroTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubirCarroTxtMouseEntered
        SubircarroBtn.setBackground(new Color(67, 180, 10));
    }//GEN-LAST:event_SubirCarroTxtMouseEntered

    private void SubirCarroTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubirCarroTxtMouseExited
        SubircarroBtn.setBackground(new Color(51,153,0));
    }//GEN-LAST:event_SubirCarroTxtMouseExited

    private void GuardarTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuardarTxtMouseClicked
        
        if(CodigoProducto.getText().equals("Ingrese el codigo de producto")&&
                Marca.getText().equals("Ingrese la marca")&&
                Modelo.getText().equals("Ingrese el modelo")&&
                AiodeFabricacion.getText().equals("Ingrese el año de fabricacion")&&
                Transmicion.getText().equals("Ingrese la transmicion")&&
                Combustible.getText().equals("Ingrese el combustible")&&
                Precio.getText().equals("Ingrese el precio de alquiler x dia")&&
                Seguro.getText().equals("Ingrese el seguro")&&
                CodigoPlaca.getText().equals("Ingrese el codigo de placa")){
            JOptionPane.showMessageDialog(null,"Complete los datos",
                    "ERROR",JOptionPane.INFORMATION_MESSAGE);
        }
        /*
        else if(CodigoProducto.getText().equals("")&&
                Marca.getText().equals("")&&
                Modelo.getText().equals("")&&
                AiodeFabricacion.getText().equals("")&&
                Transmicion.getText().equals("")&&
                Combustible.getText().equals("")&&
                Precio.getText().equals("")&&
                Seguro.getText().equals("")&&
                CodigoPlaca.getText().equals("")){
                    JOptionPane.showMessageDialog(null,"Complete los datos",
                    "ERROR",JOptionPane.ERROR_MESSAGE);
                }
        */
        //Vehiculo v = new Vehiculo();
        
        String respuesta=GuardarArchivo(CodigoProducto+".png",this.imagen);
        if(respuesta!=null){
            JOptionPane.showMessageDialog(null,respuesta);
        
}
    }//GEN-LAST:event_GuardarTxtMouseClicked

    private void GuardarTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuardarTxtMouseEntered
        GuardarBtn.setBackground(new Color(67, 180, 10));
    }//GEN-LAST:event_GuardarTxtMouseEntered

    private void GuardarTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuardarTxtMouseExited
        GuardarBtn.setBackground(new Color(51,153,0));
    }//GEN-LAST:event_GuardarTxtMouseExited

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen()-60;
        int y = evt.getYOnScreen();
        this.setLocation(x  - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void exitTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitTxtMouseClicked

    private void exitTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseEntered
        exitBtn.setBackground(Color.red);
        exitTxt.setForeground(Color.white);
    }//GEN-LAST:event_exitTxtMouseEntered

    private void exitTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseExited
        exitBtn.setBackground(Color.white);
        exitTxt.setForeground(Color.black);
    }//GEN-LAST:event_exitTxtMouseExited

    private void hideTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hideTxtMouseClicked
        setExtendedState(ICONIFIED);
    }//GEN-LAST:event_hideTxtMouseClicked

    private void hideTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hideTxtMouseEntered
        hideBtn.setBackground(Color.blue);
        hideTxt.setForeground(Color.white);
    }//GEN-LAST:event_hideTxtMouseEntered

    private void hideTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hideTxtMouseExited
        hideBtn.setBackground(Color.white);
        hideTxt.setForeground(Color.black);
    }//GEN-LAST:event_hideTxtMouseExited

    private void backTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backTxtMouseClicked
        dispose();
        new MenuAdministrador().setVisible(true);
    }//GEN-LAST:event_backTxtMouseClicked

    private void backTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backTxtMouseEntered
        backBtn.setBackground(Color.red);
        backTxt.setForeground(Color.white);
    }//GEN-LAST:event_backTxtMouseEntered

    private void backTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backTxtMouseExited
        backBtn.setBackground(Color.white);
        backTxt.setForeground(Color.black);
    }//GEN-LAST:event_backTxtMouseExited

    private void OpVehiculoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_OpVehiculoItemStateChanged
        String OpA = (String) OpVehiculo.getSelectedItem();
        if(OpA=="Transporte"){
            JTransporte t= new JTransporte();
            t.setSize(580,170);
            t.setLocation(0,0);
            ContenidoT.removeAll();
            ContenidoT.add(t,AbsoluteLayout.class);
            ContenidoT.revalidate();
            ContenidoT.repaint();
            TipoDeVehiculo2.setText("Vehiculo de Tranporte :");
            OpTransporte.setVisible(true);
            OpCarga.setVisible(false);
            ContenidoToC.removeAll();
            ContenidoToC.revalidate();
            ContenidoToC.repaint();
            
        }
        else if(OpA=="Carga"){
            JCarga c= new JCarga();
            c.setSize(580,170);
            c.setLocation(0,0);
            ContenidoT.removeAll();
            ContenidoT.add(c,AbsoluteLayout.class);
            ContenidoT.revalidate();
            ContenidoT.repaint();
            TipoDeVehiculo2.setText("Vehiculo de Carga :");
            OpCarga.setVisible(true);
            OpTransporte.setVisible(false);
            ContenidoToC.removeAll();
            ContenidoToC.revalidate();
            ContenidoToC.repaint();
            
        }
        else{
            ContenidoT.removeAll();
            ContenidoT.revalidate();
            ContenidoT.repaint();
            OpCarga.setVisible(false);
            OpTransporte.setVisible(false);
            TipoDeVehiculo2.setText("");
            ContenidoToC.removeAll();
            ContenidoToC.revalidate();
            ContenidoToC.repaint();
        }
    }//GEN-LAST:event_OpVehiculoItemStateChanged

    private void OpCargaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_OpCargaItemStateChanged
        String OpC =(String)OpCarga.getSelectedItem();
            if(OpC=="Camion"){
      
                JCCamion cc= new JCCamion();
                cc.setSize(580,350);
                cc.setLocation(0,0);
                ContenidoToC.removeAll();
                ContenidoToC.add(cc,AbsoluteLayout.class);
                ContenidoToC.revalidate();
                ContenidoToC.repaint();
            
            }
            else if(OpC=="Trailer"){
                JCTrailer ct= new JCTrailer();
                ct.setSize(580,350);
                ct.setLocation(0,0);
                ContenidoToC.removeAll();
                ContenidoToC.add(ct,AbsoluteLayout.class);
                ContenidoToC.revalidate();
                ContenidoToC.repaint();
            }

            else{
                ContenidoToC.removeAll();
                ContenidoToC.revalidate();
                ContenidoToC.repaint();
            }
    }//GEN-LAST:event_OpCargaItemStateChanged

    private void OpTransporteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_OpTransporteItemStateChanged
        String OpT =(String)OpTransporte.getSelectedItem();
            if(OpT=="Auto"){
      
                JTAuto ta = new JTAuto ();
                ta.setSize(580,350);
                ta.setLocation(0,0);
                ContenidoToC.removeAll();
                ContenidoToC.add(ta,AbsoluteLayout.class);
                ContenidoToC.revalidate();
                ContenidoToC.repaint();
            
            }
            else if(OpT=="Bus"){
                JTBus tb= new JTBus();
                tb.setSize(580,350);
                tb.setLocation(0,0);
                ContenidoToC.removeAll();
                ContenidoToC.add(tb,AbsoluteLayout.class);
                ContenidoToC.revalidate();
                ContenidoToC.repaint();
            }
            else if(OpT=="Moto"){
                JTMoto tm= new JTMoto();
                tm.setSize(580,350);
                tm.setLocation(0,0);
                ContenidoToC.removeAll();
                ContenidoToC.add(tm,AbsoluteLayout.class);
                ContenidoToC.revalidate();
                ContenidoToC.repaint();
            }

            else{
                ContenidoToC.removeAll();
                ContenidoToC.revalidate();
                ContenidoToC.repaint();
            }
    }//GEN-LAST:event_OpTransporteItemStateChanged

    private void CodigoProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CodigoProductoMouseClicked
        CodigoProducto();
    }//GEN-LAST:event_CodigoProductoMouseClicked

    private void CodigoProductoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CodigoProductoKeyPressed
        CodigoProducto();
    }//GEN-LAST:event_CodigoProductoKeyPressed

    private void CodigoProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CodigoProductoKeyTyped
        CodigoProducto();
    }//GEN-LAST:event_CodigoProductoKeyTyped

    private void MarcaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MarcaMouseClicked
        Marca();
    }//GEN-LAST:event_MarcaMouseClicked

    private void MarcaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MarcaKeyPressed
        Marca();
    }//GEN-LAST:event_MarcaKeyPressed

    private void MarcaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MarcaKeyTyped
        Marca();
    }//GEN-LAST:event_MarcaKeyTyped

    private void ModeloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModeloMouseClicked
        Modelo();
    }//GEN-LAST:event_ModeloMouseClicked

    private void ModeloKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ModeloKeyPressed
        Modelo();
    }//GEN-LAST:event_ModeloKeyPressed

    private void ModeloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ModeloKeyTyped
        Modelo();
    }//GEN-LAST:event_ModeloKeyTyped

    private void AiodeFabricacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AiodeFabricacionMouseClicked
        AiodeFabricacion();
    }//GEN-LAST:event_AiodeFabricacionMouseClicked

    private void AiodeFabricacionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AiodeFabricacionKeyPressed
        AiodeFabricacion();
    }//GEN-LAST:event_AiodeFabricacionKeyPressed

    private void AiodeFabricacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AiodeFabricacionKeyTyped
        AiodeFabricacion();
    }//GEN-LAST:event_AiodeFabricacionKeyTyped

    private void TransmicionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TransmicionMouseClicked
        Transmicion();
    }//GEN-LAST:event_TransmicionMouseClicked

    private void TransmicionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TransmicionKeyPressed
        Transmicion();
    }//GEN-LAST:event_TransmicionKeyPressed

    private void TransmicionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TransmicionKeyTyped
        Transmicion();
    }//GEN-LAST:event_TransmicionKeyTyped

    private void CombustibleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CombustibleMouseClicked
        Combustible();
    }//GEN-LAST:event_CombustibleMouseClicked

    private void CombustibleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CombustibleKeyPressed
        Combustible();
    }//GEN-LAST:event_CombustibleKeyPressed

    private void CombustibleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CombustibleKeyTyped
        Combustible();
    }//GEN-LAST:event_CombustibleKeyTyped

    private void PrecioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PrecioMouseClicked
        Precio();
    }//GEN-LAST:event_PrecioMouseClicked

    private void PrecioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PrecioKeyPressed
        Precio();
    }//GEN-LAST:event_PrecioKeyPressed

    private void PrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PrecioKeyTyped
        Precio();
    }//GEN-LAST:event_PrecioKeyTyped

    private void SeguroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SeguroMouseClicked
        Seguro();
    }//GEN-LAST:event_SeguroMouseClicked

    private void SeguroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SeguroKeyPressed
        Seguro();
    }//GEN-LAST:event_SeguroKeyPressed

    private void SeguroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SeguroKeyTyped
        Seguro();
    }//GEN-LAST:event_SeguroKeyTyped

    private void CodigoPlacaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CodigoPlacaMouseClicked
        CodigoPlaca();
    }//GEN-LAST:event_CodigoPlacaMouseClicked

    private void CodigoPlacaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CodigoPlacaKeyPressed
        CodigoPlaca();
    }//GEN-LAST:event_CodigoPlacaKeyPressed

    private void CodigoPlacaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CodigoPlacaKeyTyped
        CodigoPlaca();
    }//GEN-LAST:event_CodigoPlacaKeyTyped
    private void CodigoProducto(){
        if (String.valueOf(CodigoProducto.getText()).equals("Ingrese el codigo de producto")) {
            CodigoProducto.setText("");
            CodigoProducto.setForeground(Color.black);
        }
        if (Marca.getText().isEmpty()) {
            Marca.setText("Ingrese la marca");
            Marca.setForeground(Color.gray);
        }
        if (Modelo.getText().isEmpty()) {
            Modelo.setText("Ingrese el modelo");
            Modelo.setForeground(Color.gray);
        }
        if (AiodeFabricacion.getText().isEmpty()) {
            AiodeFabricacion.setText("Ingrese el año de fabricacion");
            AiodeFabricacion.setForeground(Color.gray);
        }
        if (Transmicion.getText().isEmpty()) {
            Transmicion.setText("Ingrese la transmicion");
            Transmicion.setForeground(Color.gray);
        }
        if (Combustible.getText().isEmpty()) {
            Combustible.setText("Ingrese el combustible");
            Combustible.setForeground(Color.gray);
        }
        if (Precio.getText().isEmpty()) {
            Precio.setText("Ingrese el precio de alquiler x dia");
            Precio.setForeground(Color.gray);
        }
        if (Seguro.getText().isEmpty()) {
            Seguro.setText("Ingrese el seguro");
            Seguro.setForeground(Color.gray);
        }
        if (CodigoPlaca.getText().isEmpty()) {
            CodigoPlaca.setText("Ingrese el codigo de placa");
            CodigoPlaca.setForeground(Color.gray);
        }
    }
    private void Marca(){
        if (String.valueOf(Marca.getText()).equals("Ingrese la marca")) {
            Marca.setText("");
            Marca.setForeground(Color.black);
        }
        if (CodigoProducto.getText().isEmpty()) {
            CodigoProducto.setText("Ingrese el codigo de producto");
            CodigoProducto.setForeground(Color.gray);
        }
        if (Modelo.getText().isEmpty()) {
            Modelo.setText("Ingrese el modelo");
            Modelo.setForeground(Color.gray);
        }
        if (AiodeFabricacion.getText().isEmpty()) {
            AiodeFabricacion.setText("Ingrese el año de fabricacion");
            AiodeFabricacion.setForeground(Color.gray);
        }
        if (Transmicion.getText().isEmpty()) {
            Transmicion.setText("Ingrese la transmicion");
            Transmicion.setForeground(Color.gray);
        }
        if (Combustible.getText().isEmpty()) {
            Combustible.setText("Ingrese el combustible");
            Combustible.setForeground(Color.gray);
        }
        if (Precio.getText().isEmpty()) {
            Precio.setText("Ingrese el precio de alquiler x dia");
            Precio.setForeground(Color.gray);
        }
        if (Seguro.getText().isEmpty()) {
            Seguro.setText("Ingrese el seguro");
            Seguro.setForeground(Color.gray);
        }
        if (CodigoPlaca.getText().isEmpty()) {
            CodigoPlaca.setText("Ingrese el codigo de placa");
            CodigoPlaca.setForeground(Color.gray);
        }
    }
    private void Modelo(){
        if (String.valueOf(Modelo.getText()).equals("Ingrese el modelo")) {
            Modelo.setText("");
            Modelo.setForeground(Color.black);
        }
        if (CodigoProducto.getText().isEmpty()) {
            CodigoProducto.setText("Ingrese el codigo de producto");
            CodigoProducto.setForeground(Color.gray);
        }
        if (Marca.getText().isEmpty()) {
            Marca.setText("Ingrese la marca");
            Marca.setForeground(Color.gray);
        }
        if (AiodeFabricacion.getText().isEmpty()) {
            AiodeFabricacion.setText("Ingrese el año de fabricacion");
            AiodeFabricacion.setForeground(Color.gray);
        }
        if (Transmicion.getText().isEmpty()) {
            Transmicion.setText("Ingrese la transmicion");
            Transmicion.setForeground(Color.gray);
        }
        if (Combustible.getText().isEmpty()) {
            Combustible.setText("Ingrese el combustible");
            Combustible.setForeground(Color.gray);
        }
        if (Precio.getText().isEmpty()) {
            Precio.setText("Ingrese el precio de alquiler x dia");
            Precio.setForeground(Color.gray);
        }
        if (Seguro.getText().isEmpty()) {
            Seguro.setText("Ingrese el seguro");
            Seguro.setForeground(Color.gray);
        }
        if (CodigoPlaca.getText().isEmpty()) {
            CodigoPlaca.setText("Ingrese el codigo de placa");
            CodigoPlaca.setForeground(Color.gray);
        }
    }
    private void AiodeFabricacion(){
        if (String.valueOf(AiodeFabricacion.getText()).equals("Ingrese el año de fabricacion")) {
            AiodeFabricacion.setText("");
            AiodeFabricacion.setForeground(Color.black);
        }
        if (CodigoProducto.getText().isEmpty()) {
            CodigoProducto.setText("Ingrese el codigo de producto");
            CodigoProducto.setForeground(Color.gray);
        }
        if (Marca.getText().isEmpty()) {
            Marca.setText("Ingrese la marca");
            Marca.setForeground(Color.gray);
        }
        if (Modelo.getText().isEmpty()) {
            Modelo.setText("Ingrese el modelo");
            Modelo.setForeground(Color.gray);
        }
        if (Transmicion.getText().isEmpty()) {
            Transmicion.setText("Ingrese la transmicion");
            Transmicion.setForeground(Color.gray);
        }
        if (Combustible.getText().isEmpty()) {
            Combustible.setText("Ingrese el combustible");
            Combustible.setForeground(Color.gray);
        }
        if (Precio.getText().isEmpty()) {
            Precio.setText("Ingrese el precio de alquiler x dia");
            Precio.setForeground(Color.gray);
        }
        if (Seguro.getText().isEmpty()) {
            Seguro.setText("Ingrese el seguro");
            Seguro.setForeground(Color.gray);
        }
        if (CodigoPlaca.getText().isEmpty()) {
            CodigoPlaca.setText("Ingrese el codigo de placa");
            CodigoPlaca.setForeground(Color.gray);
        }
    }
    private void Transmicion(){
        if (String.valueOf(Transmicion.getText()).equals("Ingrese la transmicion")) {
            Transmicion.setText("");
            Transmicion.setForeground(Color.black);
        }
        if (CodigoProducto.getText().isEmpty()) {
            CodigoProducto.setText("Ingrese el codigo de producto");
            CodigoProducto.setForeground(Color.gray);
        }
        if (Marca.getText().isEmpty()) {
            Marca.setText("Ingrese la marca");
            Marca.setForeground(Color.gray);
        }
        if (Modelo.getText().isEmpty()) {
            Modelo.setText("Ingrese el modelo");
            Modelo.setForeground(Color.gray);
        }
        if (AiodeFabricacion.getText().isEmpty()) {
            AiodeFabricacion.setText("Ingrese el año de fabricacion");
            AiodeFabricacion.setForeground(Color.gray);
        }
        if (Combustible.getText().isEmpty()) {
            Combustible.setText("Ingrese el combustible");
            Combustible.setForeground(Color.gray);
        }
        if (Precio.getText().isEmpty()) {
            Precio.setText("Ingrese el precio de alquiler x dia");
            Precio.setForeground(Color.gray);
        }
        if (Seguro.getText().isEmpty()) {
            Seguro.setText("Ingrese el seguro");
            Seguro.setForeground(Color.gray);
        }
        if (CodigoPlaca.getText().isEmpty()) {
            CodigoPlaca.setText("Ingrese el codigo de placa");
            CodigoPlaca.setForeground(Color.gray);
        }
    }
    private void Combustible(){
        if (String.valueOf(Combustible.getText()).equals("Ingrese el combustible")) {
            Combustible.setText("");
            Combustible.setForeground(Color.black);
        }
        if (CodigoProducto.getText().isEmpty()) {
            CodigoProducto.setText("Ingrese el codigo de producto");
            CodigoProducto.setForeground(Color.gray);
        }
        if (Marca.getText().isEmpty()) {
            Marca.setText("Ingrese la marca");
            Marca.setForeground(Color.gray);
        }
        if (Modelo.getText().isEmpty()) {
            Modelo.setText("Ingrese el modelo");
            Modelo.setForeground(Color.gray);
        }
        if (AiodeFabricacion.getText().isEmpty()) {
            AiodeFabricacion.setText("Ingrese el año de fabricacion");
            AiodeFabricacion.setForeground(Color.gray);
        }
        if (Transmicion.getText().isEmpty()) {
            Transmicion.setText("Ingrese la transmicion");
            Transmicion.setForeground(Color.gray);
        }
        if (Precio.getText().isEmpty()) {
            Precio.setText("Ingrese el precio de alquiler x dia");
            Precio.setForeground(Color.gray);
        }
        if (Seguro.getText().isEmpty()) {
            Seguro.setText("Ingrese el seguro");
            Seguro.setForeground(Color.gray);
        }
        if (CodigoPlaca.getText().isEmpty()) {
            CodigoPlaca.setText("Ingrese el codigo de placa");
            CodigoPlaca.setForeground(Color.gray);
        }
    }
    private void Precio(){
        if (String.valueOf(Precio.getText()).equals("Ingrese el precio de alquiler x dia")) {
            Precio.setText("");
            Precio.setForeground(Color.black);
        }
        if (CodigoProducto.getText().isEmpty()) {
            CodigoProducto.setText("Ingrese el codigo de producto");
            CodigoProducto.setForeground(Color.gray);
        }
        if (Marca.getText().isEmpty()) {
            Marca.setText("Ingrese la marca");
            Marca.setForeground(Color.gray);
        }
        if (Modelo.getText().isEmpty()) {
            Modelo.setText("Ingrese el modelo");
            Modelo.setForeground(Color.gray);
        }
        if (AiodeFabricacion.getText().isEmpty()) {
            AiodeFabricacion.setText("Ingrese el año de fabricacion");
            AiodeFabricacion.setForeground(Color.gray);
        }
        if (Transmicion.getText().isEmpty()) {
            Transmicion.setText("Ingrese la transmicion");
            Transmicion.setForeground(Color.gray);
        }
        if (Combustible.getText().isEmpty()) {
            Combustible.setText("Ingrese el combustible");
            Combustible.setForeground(Color.gray);
        }
        if (Seguro.getText().isEmpty()) {
            Seguro.setText("Ingrese el seguro");
            Seguro.setForeground(Color.gray);
        }
        if (CodigoPlaca.getText().isEmpty()) {
            CodigoPlaca.setText("Ingrese el codigo de placa");
            CodigoPlaca.setForeground(Color.gray);
        }
    }
    private void Seguro(){
        if (String.valueOf(Seguro.getText()).equals("Ingrese el seguro")) {
            Seguro.setText("");
            Seguro.setForeground(Color.black);
        }
        if (CodigoProducto.getText().isEmpty()) {
            CodigoProducto.setText("Ingrese el codigo de producto");
            CodigoProducto.setForeground(Color.gray);
        }
        if (Marca.getText().isEmpty()) {
            Marca.setText("Ingrese la marca");
            Marca.setForeground(Color.gray);
        }
        if (Modelo.getText().isEmpty()) {
            Modelo.setText("Ingrese el modelo");
            Modelo.setForeground(Color.gray);
        }
        if (AiodeFabricacion.getText().isEmpty()) {
            AiodeFabricacion.setText("Ingrese el año de fabricacion");
            AiodeFabricacion.setForeground(Color.gray);
        }
        if (Transmicion.getText().isEmpty()) {
            Transmicion.setText("Ingrese la transmicion");
            Transmicion.setForeground(Color.gray);
        }
        if (Combustible.getText().isEmpty()) {
            Combustible.setText("Ingrese el combustible");
            Combustible.setForeground(Color.gray);
        }
        if (Precio.getText().isEmpty()) {
            Precio.setText("Ingrese el precio de alquiler x dia");
            Precio.setForeground(Color.gray);
        }
        if (CodigoPlaca.getText().isEmpty()) {
            CodigoPlaca.setText("Ingrese el codigo de placa");
            CodigoPlaca.setForeground(Color.gray);
        }
    }
    private void CodigoPlaca(){
        if (String.valueOf(CodigoPlaca.getText()).equals("Ingrese el codigo de placa")) {
            CodigoPlaca.setText("");
            CodigoPlaca.setForeground(Color.black);
        }
        if (CodigoProducto.getText().isEmpty()) {
            CodigoProducto.setText("Ingrese el codigo de producto");
            CodigoProducto.setForeground(Color.gray);
        }
        if (Marca.getText().isEmpty()) {
            Marca.setText("Ingrese la marca");
            Marca.setForeground(Color.gray);
        }
        if (Modelo.getText().isEmpty()) {
            Modelo.setText("Ingrese el modelo");
            Modelo.setForeground(Color.gray);
        }
        if (AiodeFabricacion.getText().isEmpty()) {
            AiodeFabricacion.setText("Ingrese el año de fabricacion");
            AiodeFabricacion.setForeground(Color.gray);
        }
        if (Transmicion.getText().isEmpty()) {
            Transmicion.setText("Ingrese la transmicion");
            Transmicion.setForeground(Color.gray);
        }
        if (Combustible.getText().isEmpty()) {
            Combustible.setText("Ingrese el combustible");
            Combustible.setForeground(Color.gray);
        }
        if (Precio.getText().isEmpty()) {
            Precio.setText("Ingrese el precio de alquiler x dia");
            Precio.setForeground(Color.gray);
        }
        if (Seguro.getText().isEmpty()) {
            Seguro.setText("Ingrese el seguro");
            Seguro.setForeground(Color.gray);
        }
    }
    private byte[] AbrirArchivo(File archivo){
        byte[] imagen= new byte[1024*1000];
        try{
            entrada=new FileInputStream(archivo);
            entrada.read(imagen);
        } catch(Exception e){
            System.out.println("ERROR");
        }
        return imagen;
    }
    private String GuardarArchivo(String direccion, byte[]imagen){
        String mensaje=null;
        try{
            this.salida=new FileOutputStream(direccion);
            this.salida.write(imagen);
            mensaje="Archivo Guardado";
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Archivo no guardado");
        }
        
        return mensaje;
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarVehiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AiodeFabricacion;
    private javax.swing.JLabel Carropng;
    private javax.swing.JTextField CodigoPlaca;
    private javax.swing.JTextField CodigoProducto;
    private javax.swing.JTextField Combustible;
    private javax.swing.JPanel ContenidoT;
    private javax.swing.JPanel ContenidoToC;
    private javax.swing.JPanel GuardarBtn;
    private javax.swing.JLabel GuardarTxt;
    private javax.swing.JTextField Marca;
    private javax.swing.JTextField Modelo;
    private javax.swing.JComboBox<String> OpCarga;
    private javax.swing.JComboBox<String> OpTransporte;
    private javax.swing.JComboBox<String> OpVehiculo;
    private javax.swing.JTextField Precio;
    private javax.swing.JTextField Seguro;
    private javax.swing.JLabel SubirCarroTxt;
    private javax.swing.JPanel SubircarroBtn;
    private javax.swing.JLabel TipoDeVehiculo;
    private javax.swing.JLabel TipoDeVehiculo2;
    private javax.swing.JTextField Transmicion;
    private javax.swing.JPanel backBtn;
    private javax.swing.JLabel backTxt;
    private javax.swing.JPanel exitBtn;
    private javax.swing.JLabel exitTxt;
    private javax.swing.JPanel header;
    private javax.swing.JPanel hideBtn;
    private javax.swing.JLabel hideTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    // End of variables declaration//GEN-END:variables
}
